# AnnotateRb configuration
# See: https://github.com/drwl/annotaterb

# Position of annotations
position_in_class: bottom
position_in_factory: bottom
position_in_fixture: bottom
position_in_test: bottom
position_in_serializer: bottom

# What to annotate
annotate_models: true
annotate_routes: false

# Model annotation options
show_indexes: true
show_foreign_keys: true
show_complete_foreign_keys: false
show_check_constraints: false

# Include/exclude patterns
exclude_tests: false
exclude_fixtures: false
exclude_factories: false
exclude_serializers: true

# File patterns
model_dir:
  - app/models
root_dir:
  - ''

# Format options
format_bare: true
format_rdoc: false
format_yard: false
format_markdown: false

# Misc
force: false
trace: false
wrapper_open:
wrapper_close:
with_comment: true
