root:
  - code: resource_types
    name: Resource Types
  - code: grant_types
    name: Grant Types
  - code: difficulty_levels
    name: Difficulty Levels
  - code: genres
    name: Genres
  - code: room_statuses
    name: Room Statuses
  - code: import_statuses
    name: Import Statuses
  - code: qr_statuses
    name: QR Generation Statuses